### ISSUE TITLE
Use detective-es6 for extracting dependencies

### ISSUE THREAD

**Issue by mrjoelkemp** [ndelangen/sourcejs-react-dependencies#1]
Hi there!

Just an fyi, you can replace [all of this](https://github.com/ndelangen/sourcejs-react-dependencies/blob/fecb60ce52014c4ce2ea1f997c05919662705a9f/core/middleware/extractImports.js#L27-L42) with https://www.npmjs.com/package/detective-es6. 

Nice work!

**Comment by ndelangen** [comment]
Thanks for the info. I will change out `node-source-walk` for `detective-es6`, and remove that bit of code.

**Comment by ndelangen** [comment]
[v0.0.2](https://github.com/ndelangen/sourcejs-react-dependencies/releases/tag/v0.0.2) includes this change

**Comment by mrjoelkemp** [comment]
Awesome! :+1:
